version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning


  backend:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-0ves$6-v9(%2)0ec8zlzk6_46lq*ra(u8ga*cxwlxn(5qwp$6b
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '2525:25'
      - '1143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
  
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./core/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://back:8000/
  
  worker:
    image: locustio/locust
    volumes:
      - ./core/core/locust:/mnt/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  smtp4dev-data:
