name: Django project test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd core
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          cd core
          python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} # یا از key استفاده کن اگر کلید خصوصی استفاده می‌کنی
          script: |
            cd /home/alicurese
            git pull origin main
            docker-compose -f docker-compose-stage.yml down
            docker-compose -f docker-compose-stage.yml up -d --build
            docker-compose -f docker-compose-stage.yml exec web python manage.py makemigrations
            docker-compose -f docker-compose-stage.yml exec web python manage.py migrate
            docker-compose -f docker-compose-stage.yml exec web python manage.py collectstatic --noinput
