name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: docker compose up -d --build

    - name: Run tests inside container
      run: docker compose exec -T backend bash -c "DJANGO_SETTINGS_MODULE=core.settings pytest"

    - name: Shut down containers
      run: docker compose down
